//! Shared types for upgrade directives and status reporting.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use super::marker::UpgradeMarker;
use super::version::BinaryVersion;

/// Everything a node needs to perform one upgrade. Sent by the leader (or
/// relish, single-node) to `POST /v1/upgrade/apply` as JSON.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpgradeDirective {
    /// Idempotency key, generated by whoever starts the upgrade. Re-sending
    /// a directive with the same id while it is in flight is a no-op.
    pub upgrade_id: String,
    pub target_version: BinaryVersion,
    /// Hex SHA-256 of the binary; also its content address in Pickle.
    pub binary_sha256: String,
    /// Base64 Ed25519 signature from the release key set.
    pub embedded_signature: String,
    /// Base64 Ed25519 signature from the operator's external key.
    /// `None` only for air-gapped (local file) upgrades.
    pub external_signature: Option<String>,
    pub source: BinarySource,
}

/// Where the node obtains the binary bytes.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum BinarySource {
    /// Fetch from the Pickle registry, content-addressed by
    /// `binary_sha256`. Network upgrades use this; the external
    /// signature is mandatory.
    Pickle { registry_address: String },
    /// The binary is already at this local path (air-gapped / single-node
    /// `--binary` flow). The embedded signature alone suffices.
    LocalFile { path: PathBuf },
}

impl BinarySource {
    /// Network upgrades demand the external signature; local files don't.
    pub fn is_network(&self) -> bool {
        matches!(self, BinarySource::Pickle { .. })
    }
}

/// One line of `{data_dir}/upgrade/history.jsonl`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UpgradeHistoryEntry {
    pub upgrade_id: String,
    pub from_version: BinaryVersion,
    pub to_version: BinaryVersion,
    pub outcome: UpgradeOutcome,
    /// Human-readable detail (failure reason, boot attempts, ...).
    pub detail: String,
    /// Wall-clock time the outcome was recorded.
    pub recorded_at: std::time::SystemTime,
}

/// How a node-level upgrade ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum UpgradeOutcome {
    /// The new version verified and the swap is permanent.
    Committed,
    /// The previous version is back in control.
    Reverted,
    /// The marker was inconsistent and archived without action.
    Abandoned,
}

/// Node-level upgrade status for `GET /v1/upgrade/status`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeUpgradeStatus {
    pub running_version: BinaryVersion,
    /// The in-flight marker, if an upgrade is underway on this node.
    pub in_flight: Option<UpgradeMarker>,
    /// Most recent history entries, newest last (bounded).
    pub history: Vec<UpgradeHistoryEntry>,
}
