mod owned;
pub use owned::{run_helper as run_owned_helper, run_hook as run_network_hook};

/// Rootless OCI spec modifications (Linux only).
///
/// Adjusts an OCI runtime spec to run under runc's rootless mode.
/// Adds user namespace mappings, keeps a private network namespace that an owned
/// slirp4netns helper connects, adjusts /sys to a bind mount, and
/// omits cgroups unless the caller has arranged delegation.
use super::oci::{OciIdMapping, OciMount, OciNamespace, OciSpec};
use std::path::{Path, PathBuf};

/// Modify an OCI spec for rootless runc execution.
///
/// Changes:
/// - Adds `user` namespace
/// - Keeps `network` namespace (an owned slirp4netns helper connects it)
/// - Adds UID/GID mappings (current user → container root)
/// - Adjusts `/sys` mount to `bind,ro` instead of `sysfs` (which needs privileges)
/// - Removes the rootful cgroup path because Reliaburger doesn't create a
///   delegated user scope yet
/// - Resets process user to 0:0 (mapped to current user via namespace)
pub fn make_rootless(spec: &mut OciSpec, _instance_name: &str) {
    // Add user namespace
    let has_user_ns = spec.linux.namespaces.iter().any(|ns| ns.ns_type == "user");
    if !has_user_ns {
        spec.linux.namespaces.push(OciNamespace {
            ns_type: "user".to_string(),
            path: None,
        });
    }

    // Keep the network namespace. An owned slirp4netns helper provides
    // userspace networking inside the user namespace, without root.

    // Add UID/GID mappings: map current user to container root (UID 0)
    let uid = nix::unistd::getuid().as_raw();
    let gid = nix::unistd::getgid().as_raw();

    spec.linux.uid_mappings = Some(vec![OciIdMapping {
        container_id: 0,
        host_id: uid,
        size: 1,
    }]);

    spec.linux.gid_mappings = Some(vec![OciIdMapping {
        container_id: 0,
        host_id: gid,
        size: 1,
    }]);

    // Set process user to root inside the container (mapped to current
    // user outside via the namespace)
    spec.process.user.uid = 0;
    spec.process.user.gid = 0;

    // Adjust /sys mount: sysfs requires CAP_SYS_ADMIN outside the user
    // namespace, so bind-mount the host's /sys read-only instead
    super::userns::bind_host_sys(spec);

    // Add /dev/pts for terminal support in rootless mode
    let has_devpts = spec
        .mounts
        .iter()
        .any(|m| m.destination == Path::new("/dev/pts"));
    if !has_devpts {
        spec.mounts.push(OciMount {
            destination: PathBuf::from("/dev/pts"),
            source: Some(PathBuf::from("devpts")),
            mount_type: Some("devpts".to_string()),
            options: vec![
                "nosuid".to_string(),
                "noexec".to_string(),
                "newinstance".to_string(),
                "ptmxmode=0666".to_string(),
                "mode=0620".to_string(),
            ],
        });
    }

    // runc can't create a rootless cgroup below the rootful path generated by
    // `generate_spec`. Reliaburger doesn't create a delegated user scope yet,
    // so carrying that path makes every rootless container fail at startup.
    // Resource-requiring workloads are rejected before this point.
    spec.linux.cgroups_path = None;

    // Remove resource limits: the scheduler refuses limit-requiring workloads
    // on a rootless node until delegated cgroup enforcement exists.
    spec.linux.resources = None;
}

/// Check if the current process is running as a non-root user.
pub fn is_rootless() -> bool {
    !nix::unistd::getuid().is_root()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::grill::oci::{
        OciLinux, OciMount, OciNamespace, OciProcess, OciResources, OciRoot, OciSpec, OciUser,
    };
    use std::path::PathBuf;

    fn sample_spec() -> OciSpec {
        OciSpec {
            port_mapping: None,
            root: OciRoot {
                path: "rootfs".to_string(),
                readonly: false,
            },
            process: OciProcess {
                args: vec!["sh".to_string()],
                env: vec![],
                cwd: "/".to_string(),
                user: OciUser {
                    uid: 65534,
                    gid: 65534,
                },
                capabilities: None,
                overrides: None,
            },
            mounts: vec![
                OciMount {
                    destination: PathBuf::from("/proc"),
                    source: Some(PathBuf::from("proc")),
                    mount_type: Some("proc".to_string()),
                    options: vec!["nosuid".to_string()],
                },
                OciMount {
                    destination: PathBuf::from("/sys"),
                    source: Some(PathBuf::from("sysfs")),
                    mount_type: Some("sysfs".to_string()),
                    options: vec![
                        "nosuid".to_string(),
                        "noexec".to_string(),
                        "nodev".to_string(),
                        "ro".to_string(),
                    ],
                },
            ],
            linux: OciLinux {
                namespaces: vec![
                    OciNamespace {
                        ns_type: "pid".to_string(),
                        path: None,
                    },
                    OciNamespace {
                        ns_type: "network".to_string(),
                        path: None,
                    },
                    OciNamespace {
                        ns_type: "mount".to_string(),
                        path: None,
                    },
                ],
                resources: Some(OciResources {
                    cpu: None,
                    memory: None,
                    unified: std::collections::BTreeMap::new(),
                }),
                cgroups_path: Some("/sys/fs/cgroup/test".to_string()),
                uid_mappings: None,
                gid_mappings: None,
            },
        }
    }

    #[test]
    fn make_rootless_adds_user_namespace() {
        let mut spec = sample_spec();
        make_rootless(&mut spec, "test-0");

        let has_user = spec.linux.namespaces.iter().any(|ns| ns.ns_type == "user");
        assert!(has_user);
    }

    #[test]
    fn make_rootless_keeps_network_namespace() {
        let mut spec = sample_spec();
        make_rootless(&mut spec, "test-0");

        let has_network = spec
            .linux
            .namespaces
            .iter()
            .any(|ns| ns.ns_type == "network");
        assert!(
            has_network,
            "network namespace should be kept for slirp4netns"
        );
    }

    #[test]
    fn make_rootless_adds_uid_gid_mappings() {
        let mut spec = sample_spec();
        make_rootless(&mut spec, "test-0");

        let uid_mappings = spec.linux.uid_mappings.as_ref().unwrap();
        assert_eq!(uid_mappings.len(), 1);
        assert_eq!(uid_mappings[0].container_id, 0);
        assert_eq!(uid_mappings[0].host_id, nix::unistd::getuid().as_raw());
        assert_eq!(uid_mappings[0].size, 1);

        let gid_mappings = spec.linux.gid_mappings.as_ref().unwrap();
        assert_eq!(gid_mappings.len(), 1);
        assert_eq!(gid_mappings[0].container_id, 0);
        assert_eq!(gid_mappings[0].host_id, nix::unistd::getgid().as_raw());
    }

    #[test]
    fn make_rootless_adjusts_sys_mount() {
        let mut spec = sample_spec();
        make_rootless(&mut spec, "test-0");

        let sys_mount = spec
            .mounts
            .iter()
            .find(|m| m.destination.as_path() == std::path::Path::new("/sys"))
            .unwrap();

        assert_eq!(sys_mount.mount_type, Some("none".to_string()));
        assert_eq!(sys_mount.source, Some(PathBuf::from("/sys")));
        assert!(sys_mount.options.contains(&"rbind".to_string()));
        assert!(sys_mount.options.contains(&"ro".to_string()));
    }

    #[test]
    fn make_rootless_removes_undelegated_cgroup_path() {
        let mut spec = sample_spec();
        make_rootless(&mut spec, "test-0");

        assert_eq!(spec.linux.cgroups_path, None);
    }

    #[test]
    fn make_rootless_removes_resources() {
        let mut spec = sample_spec();
        assert!(spec.linux.resources.is_some());

        make_rootless(&mut spec, "test-0");
        assert!(spec.linux.resources.is_none());
    }

    #[test]
    fn make_rootless_sets_user_to_root() {
        let mut spec = sample_spec();
        assert_eq!(spec.process.user.uid, 65534);

        make_rootless(&mut spec, "test-0");
        assert_eq!(spec.process.user.uid, 0);
        assert_eq!(spec.process.user.gid, 0);
    }

    #[test]
    fn is_rootless_detects_non_root() {
        // In CI and normal dev, we run as non-root
        if nix::unistd::getuid().as_raw() != 0 {
            assert!(is_rootless());
        } else {
            assert!(!is_rootless());
        }
    }

    #[test]
    fn make_rootless_idempotent() {
        let mut spec = sample_spec();
        make_rootless(&mut spec, "test-0");

        let ns_count_before = spec.linux.namespaces.len();
        make_rootless(&mut spec, "test-0");
        let ns_count_after = spec.linux.namespaces.len();

        // Should not add duplicate user namespace
        assert_eq!(ns_count_before, ns_count_after);
    }
}
