use std::{collections::HashMap,net::Ipv4Addr,sync::Arc,time::Duration};
use reliaburger::{onion::{service_map::ServiceMap,service_id::ServiceId,types::BackendInstance,dns::{BoundDnsResponder,DnsConfig,DnsFaultState}},wrapper::{proxy::bind_proxy,types::WrapperConfig,routing::RoutingTable},config::app::IngressSpec};
use tokio::{io::{AsyncReadExt,AsyncWriteExt},net::{TcpListener,TcpStream,UdpSocket},sync::{RwLock,watch}};
use tokio_util::sync::CancellationToken;
#[tokio::main]
async fn main(){
 let backend=TcpListener::bind("127.0.0.1:0").await.unwrap();let port=backend.local_addr().unwrap().port();
 tokio::spawn(async move {loop {let (mut sock,_)=backend.accept().await.unwrap(); tokio::spawn(async move {let mut b=[0u8;4096];let n=sock.read(&mut b).await.unwrap(); let req=String::from_utf8_lossy(&b[..n]); if req.contains(" /redirect "){sock.write_all(b"HTTP/1.1 302 Found\r\nLocation: /landing\r\nSet-Cookie: login=nonce; Path=/\r\nContent-Length: 0\r\nConnection: close\r\n\r\n").await.unwrap();} else if req.contains(" /stream "){sock.write_all(b"HTTP/1.1 200 OK\r\nContent-Type: text/event-stream\r\nTransfer-Encoding: chunked\r\n\r\n").await.unwrap(); for _ in 0..40 {if sock.write_all(b"9\r\ndata: x\n\n\r\n").await.is_err(){break;}tokio::time::sleep(Duration::from_secs(1)).await;}} else {sock.write_all(b"HTTP/1.1 200 OK\r\nContent-Length: 7\r\nConnection: close\r\n\r\nlanding").await.unwrap();}});}});
 let mut map=ServiceMap::new();map.register_app("web","default",80,None).unwrap();map.add_backend(&ServiceId::new("default","web"),BackendInstance{instance_id:"default__web-0".into(),node_ip:Ipv4Addr::LOCALHOST,host_port:port,healthy:true,local:true}).unwrap();
 let cfg=HashMap::from([(("default".into(),"web".into()),IngressSpec{host:"web.test".into(),path:None,tls:None,websocket:None,rate_limit_rps:None,rate_limit_burst:None})]);let mut table=RoutingTable::new();table.rebuild(&map,&cfg).unwrap();let shutdown=CancellationToken::new();let bound=bind_proxy(WrapperConfig{http_port:0,https_port:0,..Default::default()},Arc::new(RwLock::new(table)),shutdown.clone()).await.unwrap();let addr=bound.http_addr;tokio::spawn(bound.serve());
 let client=reqwest::Client::builder().redirect(reqwest::redirect::Policy::none()).build().unwrap();let resp=client.get(format!("http://127.0.0.1:{}/redirect",addr.port())).header("host","web.test").send().await.unwrap();let status=resp.status();let headers=resp.headers().clone();println!("redirect: status={} location={:?} set-cookie={:?} body={}",status,headers.get("location"),headers.get("set-cookie"),resp.text().await.unwrap());
 let start=std::time::Instant::now();let mut response=client.get(format!("http://127.0.0.1:{}/stream",addr.port())).header("host","web.test").send().await.unwrap();let mut count=0;loop {match response.chunk().await {Ok(Some(_))=>count+=1,Ok(None)=>{println!("stream: eof after {:?}, chunks={count}",start.elapsed());break;},Err(e)=>{println!("stream: error after {:?}, chunks={count}, error={e}",start.elapsed());break;}}}
 let upstream=UdpSocket::bind("127.0.0.1:0").await.unwrap();let upstream_addr=upstream.local_addr().unwrap();tokio::spawn(async move {let mut buf=[0;4096];let (n,peer)=upstream.recv_from(&mut buf).await.unwrap();let mut reply=buf[..n].to_vec();reply[2]=0x83;reply[3]=0x80;upstream.send_to(&reply,peer).await.unwrap();});
 let resolver=BoundDnsResponder::bind(DnsConfig{listen_addr:"127.0.0.1:0".parse().unwrap(),upstream:upstream_addr,..Default::default()}).await.unwrap();let dns_addr=resolver.local_addr().unwrap();tokio::spawn(resolver.run(watch::channel(map).1,watch::channel(DnsFaultState::default()).1,shutdown.clone()));let query=b"\x12\x34\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x07example\x03com\x00\x00\x01\x00\x01";let udp=UdpSocket::bind("127.0.0.1:0").await.unwrap();udp.send_to(query,dns_addr).await.unwrap();let mut buf=[0;4096];let(n,_)=udp.recv_from(&mut buf).await.unwrap();println!("external UDP: bytes={n} rcode={} tc={}",buf[3]&15,buf[2]&2!=0);let mut tcp=TcpStream::connect(dns_addr).await.unwrap();tcp.write_all(&(query.len() as u16).to_be_bytes()).await.unwrap();tcp.write_all(query).await.unwrap();let size=tcp.read_u16().await.unwrap();let mut response=vec![0;size as usize];tcp.read_exact(&mut response).await.unwrap();println!("external TCP retry: rcode={}",response[3]&15);shutdown.cancel();
}
