use std::{collections::HashMap,net::Ipv4Addr,sync::Arc,time::Duration};
use reliaburger::{onion::{service_map::ServiceMap,service_id::ServiceId,types::BackendInstance,catalog::{EndpointCatalog,CatalogBackend}},wrapper::routing::{RoutingTable,ProbeTracker,HealthProbeConfig,run_health_probes},config::app::IngressSpec,ketchup::{log_store::LogStore,types::{LogRecord,LogStream,CapturePosition}},meat::NodeId};
use tokio::{net::TcpListener,sync::RwLock};
use tokio_util::sync::CancellationToken;
#[tokio::main]
async fn main(){
 let mut map=ServiceMap::new();map.register_app("web","default",80,None).unwrap();map.add_backend(&ServiceId::new("default","web"),BackendInstance{instance_id:"default__web-0".into(),node_ip:Ipv4Addr::LOCALHOST,host_port:9,healthy:true,local:true}).unwrap();let configs=HashMap::from([(("default".into(),"web".into()),IngressSpec{host:"web.test".into(),path:None,tls:None,websocket:None,rate_limit_rps:None,rate_limit_burst:None})]);let mut table=RoutingTable::new();table.rebuild(&map,&configs).unwrap();let table=Arc::new(RwLock::new(table));let shutdown=CancellationToken::new();tokio::spawn(run_health_probes(table.clone(),HealthProbeConfig{interval:Duration::from_millis(20),timeout:Duration::from_millis(10),threshold_unhealthy:1,..Default::default()},shutdown.clone()));tokio::time::sleep(Duration::from_millis(100)).await;println!("probe before rebuild: routable={}",table.read().await.lookup("web.test","/").unwrap().healthy_count());table.write().await.rebuild(&map,&configs).unwrap();tokio::time::sleep(Duration::from_millis(100)).await;println!("probe after rebuild and more failures: routable={}",table.read().await.lookup("web.test","/").unwrap().healthy_count());shutdown.cancel();
 let root=std::path::PathBuf::from(format!("/tmp/rb-log-repro-{}",std::process::id()));std::fs::create_dir_all(&root).unwrap();let capture=root.join("stdout.log");std::fs::write(&capture,"lost\nkept\n").unwrap();let dir=root.join("logs");std::fs::write(&dir,b"blocking file").unwrap();let mut store=LogStore::new(dir.clone());let lost=LogRecord{app:"web".into(),namespace:"default".into(),instance:"default__web-0".into(),stream:LogStream::Stdout,line:"lost".into(),position:Some(CapturePosition{file:capture.clone(),end_offset:5})};store.ingest_at(100,&lost);println!("failed flush result={:?} buffered={}",store.flush().await,store.buffer_len());std::fs::remove_file(&dir).unwrap();std::fs::create_dir(&dir).unwrap();println!("replay lost row after failed flush accepted={}",store.ingest_at(101,&lost));let kept=LogRecord{line:"kept".into(),position:Some(CapturePosition{file:capture.clone(),end_offset:10}),..lost.clone()};store.ingest_at(102,&kept);store.flush().await.unwrap();let reopened=LogStore::new(dir.clone());println!("reopened log checkpoint offset={:?}",reopened.capture_offsets().get(&capture));println!("rows after recovery={:?}",reopened.query_sql_json_bounded("SELECT line FROM logs").await.unwrap());
 let service=ServiceId::new("default","crowded");let catalog=EndpointCatalog::rebuild([(service.clone(),80,(0..33).map(|i|CatalogBackend{execution:None,node_id:format!("node-{i}"),node_ip:Ipv4Addr::new(10,0,0,i+1),host_port:10000,healthy:true}).collect())]).unwrap();let merged=ServiceMap::new().with_cluster_catalog(&catalog);let snapshot:Vec<_>=merged.resolve_all().iter().map(|x|(*x).clone()).collect();println!("33 cluster backends: merged={} validation={:?}",merged.resolve(&service).unwrap().backends.len(),ServiceMap::from_snapshot(&snapshot).err());std::fs::remove_dir_all(root).unwrap();
}
