name = "demo-process-1000000"
namespace = "default"
[[cohort]]
name = "commands"
count = 1000000
chunk_size = 1000
max_attempts = 3
per_node_concurrency = 27
[cohort.template]
runtime = "process"
exec = "/tmp/rb-host-executor-v3/host/busybox"
command = ["true"]
cpu = "100m-1000m"
memory = "32Mi"
